### ISSUE TITLE
Error "Invalid JSON in 'text' parameter"?

### ISSUE THREAD

**Issue by chrisboland** [sirws/OpenData-MapServiceLayerRegistrar#1]
I've been using this script successfully for the last 9 months or so, but recently (about the last month), I've been receiving the following error, which causes the script to fail to produce any new layers in my ArcGIS online account.  I've tried running the script on a couple of Map Services and from a couple different computers with the same result.  Any ideas?
{'error': {'messageCode': 'CONT_0057', 'message': "Invalid JSON in 'text' parameter.", 'code': 400, 'details': []}}

**Comment by sirws** [comment]
Hi Chris!  I will try and take a look at this today...

**Comment by sirws** [comment]
Chris,
Please try the new version which is here:
https://github.com/sirws/OpenData-MapServiceLayerRegistrar/blob/master/registerLayers2.py

You will need to download the latest version of ArcREST (v2) from here to make it work:
https://github.com/Esri/ArcREST

Please let me know if you run into any issues with it.
